In [17]:
import torch
from torch.optim import Adam

torch.manual_seed(0)
x = torch.randn(3)
print(x)
_layer = torch.nn.Linear(3, 2)
rt = _layer(x)
print(rt)
print(_layer.weight)
label = 1
index = rt.argmax(-1)
print(index)
loss = (rt[index] - label) ** 2 
print(loss)

optim = Adam(_layer.parameters())
optim.zero_grad()
loss.backward()
optim.step()
print(_layer.weight)

tensor([ 1.5410, -0.2934, -2.1788])
tensor([0.0184, 0.8415], grad_fn=<ViewBackward0>)
Parameter containing:
tensor([[-0.0512,  0.1528, -0.1745],
        [-0.1135, -0.5516, -0.3824]], requires_grad=True)
tensor(1)
tensor(0.0251, grad_fn=<PowBackward0>)
Parameter containing:
tensor([[-0.0512,  0.1528, -0.1745],
        [-0.1125, -0.5526, -0.3834]], requires_grad=True)


In [51]:

import torch
torch.manual_seed(8)
w1 = torch.randn(1, requires_grad=True)
print(w1)
x = torch.tensor(2.0)
w2 = torch.randn(1, requires_grad=True)
print(w2)
y = x * w1 * w2
print(y)

y.backward()
print(w1.grad)
print(w2.grad)

tensor([0.2713], requires_grad=True)
tensor([-1.2729], requires_grad=True)
tensor([-0.6906], grad_fn=<MulBackward0>)
tensor([-2.5458])
tensor([0.5426])
